# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "charges", :force => true do |t|
  end

  create_table "clients", :force => true do |t|
    t.column "first_name", :string
    t.column "last_name",  :string
    t.column "company_id", :integer
  end

  create_table "companies", :force => true do |t|
    t.column "name", :string
  end

  create_table "invoices", :force => true do |t|
    t.column "date",       :datetime
    t.column "project_id", :integer
  end

  create_table "projects", :force => true do |t|
    t.column "name",       :string
    t.column "company_id", :integer
  end

end
