set softtabstop=2 
set shiftwidth=2
set tabstop=2
set expandtab
set guifont=Courier_New:h10:cANSI
set bs=2
set nocp
syntax enable
colorscheme ir_black

nnoremap  :bnext
nnoremap  :bprev
noremap c :clo!
noremap <C-s> :w<CR>
inoremap <C-s> <Esc>:w<CR>
noremap <C-f> :FuzzyFinderTextMate<CR>
noremap <C-x> :BufOnly<CR>
noremap <C-z> :NERDTreeToggle<CR>

let g:fuzzy_roots=["C:/Inetpub/wwwroot/egd_billing/", "C:/Inetpub/wwwroot/adam_soltys/"]
let g:fuzzy_matching_limit=20

autocmd GUIEnter * simalt ~X
autocmd VimLeave * NERDTreeClose
autocmd VimLeave * mks! ~/last.vim
autocmd BufWritePost ~/_vimrc :source ~/_vimrc
autocmd BufEnter * set ai
autocmd BufEnter * set si
